import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { extname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
const root=fileURLToPath(new URL('.',import.meta.url)), publicDir=join(root,'public');
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'};
async function body(req){let s='';for await(const c of req)s+=c;if(s.length>2e6)throw Error('请求过大');return JSON.parse(s||'{}')}
function json(res,status,data,extra={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...extra});res.end(JSON.stringify(data))}
async function handler(req,res){const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/api/models'){const models=JSON.parse(process.env.TEAM_MODELS||'[ {"value":"gpt-6-astra","label":"6 Astra"},{"value":"gpt-5.6-sol","label":"5.6 Sol"},{"value":"gpt-5.6-terra","label":"5.6 Terra"},{"value":"gpt-5.6-luna","label":"5.6 Luna"} ]');return json(res,200,{models})}if(req.method==='POST'&&url.pathname==='/api/chat'){const b=await body(req),base=String(b.baseUrl||'').trim().replace(/\/$/,''),key=String(b.apiKey||'').trim(),model=String(b.model||'').trim(),messages=Array.isArray(b.messages)?b.messages.slice(-50):[];if(!base||!key||!model||!messages.length)return json(res,400,{error:'请填写接口地址、API Key、模型并发送消息'});const endpoint=/\/chat\/completions$/.test(base)?base:base+'/chat/completions';const up=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${key}`},body:JSON.stringify({model,messages,temperature:Number.isFinite(+b.temperature)?+b.temperature:.7,max_tokens:Number.isFinite(+b.maxTokens)?+b.maxTokens:2048,stream:false})});const raw=await up.text();let d;try{d=JSON.parse(raw)}catch{d={error:raw.slice(0,500)}}if(!up.ok)return json(res,up.status,{error:d?.error?.message||d?.error||'模型接口调用失败'});return json(res,200,{content:d?.choices?.[0]?.message?.content||d?.output_text||'',model:d.model||model,usage:d.usage||null})}if(req.method==='GET'){let p=url.pathname==='/'?'/index.html':url.pathname;try{const data=await readFile(join(publicDir,p));res.writeHead(200,{'Content-Type':mime[extname(p)]||'application/octet-stream'});return res.end(data)}catch{res.writeHead(404);return res.end('Not found')}}json(res,404,{error:'接口不存在'})}
const server=createServer((req,res)=>handler(req,res).catch(e=>json(res,500,{error:e.message||'服务异常'})));server.listen(process.env.PORT||4180,process.env.HOST||'127.0.0.1',()=>console.log('模型对话平台已启动'));
